### ISSUE TITLE
fx25-kiss-tnc does not interoperate with other FX.25 implementations

### ISSUE THREAD

**Issue by danak6jq** [amedes/fx25-kiss-tnc#1]
Direwolf's dev branch has FX.25 support, but test frames generated with Direwolf are only decoded as AX.25 frames in fx25-kiss-tnc; to validate this, I disabled the ax25_rx() path in main.c (commented out the call to ax25_rx()), then disabled the AX.25 decoding in fx25_rx() by adding the '0 &&' in the following code around line 607 of main.c:

`	    if (0 && (ax25_len > 2) && ax25_fcs_check(ax25_buf, ax25_len)) {
#ifdef CONFIG_TNC_DEMO_MODE
	    	output_fx25_info(tag_no, ax25_buf, ax25_len, fx25_buf, NULL, 0);`

With these changes, the TNC does not decode FX.25 frames from Direwolf.

I validated that rs_result was -1 in this code around line 636 of main.c:

`		int rs_result = fx25_rsdecode(fx25_buf, tag_no); // RS error correction
`

I also attempted to decode the test file http://www.dk3wn.info/sounds/ande2_test.wav and found that FX.25 decoding is not being done, though the TNC does decode the AX.25.

It also appears the AX.25 decoding in fx25_rx() is not as successful as the AX.25 decoding in ax25_rx().

**Comment by danak6jq** [comment]
Also note that FX.25 frames produced by fx25-kiss-tnc are only decoded as AX.25 by direwolf-dev; the FX.25 decode fails in each case (RS decode -1).

**Comment by amedes** [comment]
@danak6jq Thank you for your comments.
I will fix the fx25-kiss-tnc FX.25 code to adapt Direwolf's FX.25 specification.
Thanks,

**Comment by amedes** [comment]
fixed the incompatibility problem with Direwolf's FX.25 packet
